// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using TodoApp;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace TodoApp.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(ITodoAppService), typeof(TodoClientProxy))]
public partial class TodoClientProxy : ClientProxyBase<ITodoAppService>, ITodoAppService
{
    public virtual async Task<List<TodoItemDto>> GetListAsync()
    {
        return await RequestAsync<List<TodoItemDto>>(nameof(GetListAsync));
    }

    public virtual async Task<TodoItemDto> CreateAsync(string text)
    {
        return await RequestAsync<TodoItemDto>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(string), text }
        });
    }

    public virtual async Task DeleteAsync(Guid id)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), id }
        });
    }
}
